### ISSUE TITLE
Run `apls.py` first time error

### ISSUE THREAD

**Issue by antran89** [CosmiQ/apls#6]
Hi,

When I run `python apls.py` as in the README file, it will generate the following errors. Please fix.
I use `networkx==2.2` library.

```
Traceback (most recent call last):
  File "apls.py", line 1648, in <module>
    main()
  File "apls.py", line 1275, in main
    verbose=verbose)
  File "apls.py", line 722, in create_gt_graph
    super_verbose=False)
  File "apls.py", line 653, in clean_sub_graphs
    for u,v in all_lengths.iteritems():
AttributeError: 'generator' object has no attribute 'iteritems'
```
Thanks.

**Comment by avanetten** [comment]
I am guessing that you are using python 3.  We built APLS with python 2, and haven't yet ported it to python 3.  The python 3 version should be coming soon.

**Comment by antran89** [comment]
Hi @avanetten,
I am using python2
```
MAC:~ an.tran$ python
Python 2.7.15 (default, Sep 18 2018, 20:16:18)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by avanetten** [comment]
The issue is networkx 2.2.  The apls_environment.yml file uses networkx 1.11, which treats iterators differently than networkx 2.2.  Once we update the code to python 3, we will also use the most recent version of networkx, but for now I recommend just invoking the included environment with: 
conda env create -f apls_environment.yml  
source activate apls_environment

**Comment by antran89** [comment]
Any updates on this thread. Thanks.
